<a href="https://colab.research.google.com/github/aditya0335/DIC-Assignment1/blob/master/DIC_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive



*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@c177635e71d9.(none)')


Drive-bansaladitya0335@gmail.com

In [0]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
os.chdir('/content/drive/My Drive/DIC ASSIGNMENT 1')
data=pd.read_csv('data.csv')
features=data.iloc[:,0:48]
labels=data.iloc[:,48]
features_train,features_test,labels_train,labels_test=train_test_split(features,labels,test_size=0.2)

In [18]:
!git clone https://github.com/Deepesh7/Predictive-Analysis.git

fatal: remote origin already exists.


In [0]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report 
from sklearn import preprocessing
from sklearn.preprocessing import scale
from sklearn.preprocessing import MinMaxScaler
# features = preprocessing.normalize(features)
# features=scale(features)

In [48]:
features=np.asarray(features)
features_train=np.asarray(features_train)
features_test=np.asarray(features_test)
labels_train=np.asarray(labels_train)
labels_test=np.asarray(labels_test)
print(features_test.shape)
print(features_train.shape)
# features_test_repeat=np.repeat(features_test,32764,0)
# print(features_test_repeat.shape)
row=features_train[:1,]
print(row.shape)
scaler = MinMaxScaler()
features_train=scaler.fit_transform(features_train)
features_test=scaler.transform(features_test)

# for row in features_test:
#   print(np.tile(row,reps=[32764,1])-features_train)
  
# features_train_repeat=np.tile(features_train,reps=)

(8192, 48)
(32764, 48)
(1, 48)


In [0]:
def KNN(X_train,X_test,Y_train):
  testresult=[]
  k_value=50
  b=0
  testresult_test=[]
  for row in X_test:
    distance=[]
    knn = []
    row=np.asarray(row)
    row=row.reshape(1,48)
    
    # distance=np.sqrt(np.sum(np.subtract(np.tile(row,reps=[32764,1]),X_train),axis=1),axis=1)
    distance=np.sqrt(np.sum(np.square((np.subtract(np.repeat(row,32764,0),X_train))),axis=1))
    distance=distance.reshape(32764,1)
    Y_train=Y_train.reshape(32764,1)
    distance_Y_train=np.concatenate((Y_train,distance),axis=1)
    distance_Y_train =  distance_Y_train[np.argsort(distance_Y_train[:, 1])]    
    knn = distance_Y_train[:k_value]
    knn=knn[:,0]
    knn=knn.astype(int)
    # print(np.bincount(knn).argmax())
    testresult_test=np.append(testresult_test,np.bincount(knn).argmax())
  return testresult_test
result=KNN(features_train,features_test,labels_train)


In [80]:
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

print(accuracy_score(labels_test,result))


0.9776611328125


Deepesh

In [0]:
# -*- coding: utf-8 -*-
"""
Predicitve_Analytics.py
"""


def Accuracy(y_true,y_pred):
  size=y_true.size
  
    # """
    # :type y_true: numpy.ndarray
    # :type y_pred: numpy.ndarray
    # :rtype: float
    
    # """

Pooja

In [109]:
from sklearn.metrics import recall_score

def Recall(y_true,y_pred):
  classes=np.unique(y_true)
  size=len(y_pred)
  true_positive=0
  false_negative=0
  recall=0
  for c in classes:
    for i in range(size):
      if y_true[i]==c and y_pred[i]==c:
        true_positive +=1
      if y_true[i]==c and y_pred[i]!=c:
        false_negative +=1
    if (true_positive==0 and false_negative==0):
      recall=0
    else:
      recall+=true_positive/(true_positive+false_negative)
  return recall/len(classes)
result=result.astype(int)
print(Recall(labels_test,result))
print(recall_score(labels_test,result,average='macro'))
    #  """
    # :type y_true: numpy.ndarray
    # :type y_pred: numpy.ndarray
    # :rtype: float
    # """



0.9787535343396627
0.9779098872944286


Aditya

In [110]:
from sklearn.metrics import precision_score

def Precision(y_true,y_pred):
  classes=np.unique(y_true)
  size=len(y_pred)
  true_positive=0
  false_positive=0
  precision=0
  for c in classes:
    for i in range(size):
      if y_true[i]==c and y_pred[i]==c:
        true_positive +=1
      if y_true[i]!=c and y_pred[i]==c:
        false_positive +=1
    if (true_positive==0 and false_positive==0):
      precision=0
    else:
      precision+=true_positive/(true_positive+false_positive)
  return precision/len(classes)
result=result.astype(int)

print(Precision(labels_test,result))
print(precision_score(labels_test,result,average='macro'))


0.9730574853928385
0.9781589935498108


In [0]:
def WCSS(Clusters):
    """
    :Clusters List[numpy.ndarray]
    :rtype: float
    """

In [89]:
def ConfusionMatrix(y_true,y_pred):
  unique_val=np.unique(y_true)
  no_class = len(unique_val)
  y_true=y_true-1
  y_pred=y_pred-1

  confusion_matrix=y_true*no_class+y_pred
  con_matrix= np.zeros(no_class**2)
  for i in range(len(confusion_matrix)): 
    index=confusion_matrix[i]
    count=np.count_nonzero(confusion_matrix==(index))
    con_matrix[index]=count

  con_matrix_reshape=np.reshape(con_matrix, (no_class,no_class))
  return con_matrix_reshape

result=result.astype(int)
print(ConfusionMatrix(labels_test,result))  
    # """
    # :type y_true: numpy.ndarray
    # :type y_pred: numpy.ndarray
    # :rtype: float
    # """ 


(8192,)
(8192,)
[[709.   0.   0.   0.   0.  20.   0.   0.   0.   0.   0.]
 [  1. 712.   0.   0.   0.   0.   0.   0.   1.  24.   0.]
 [  0.   0. 705.   1.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   1. 732.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   0.   2.   9. 706.   0.   0.   7.   0.   0.   0.]
 [  7.   0.   0.   0.   0. 758.   0.   0.   9.   0.   0.]
 [  0.   0.   0.   0.   0.   0. 775.   0.   0.   0.   0.]
 [  0.   0.   0.   3.  12.   1.   0. 730.   0.   0.   0.]
 [  3.   2.   0.   0.   0.  28.   0.   0. 728.   1.   0.]
 [  0.  50.   0.   0.   0.   0.   0.   0.   0. 724.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0. 730.]]


Aditya

RANDOM FOREST

In [0]:
features_train=np.asarray(features_train)
features_test=np.asarray(features_test)
labels_train=np.asarray(labels_train)
labels_test=np.asarray(labels_test)

def gini_number(data):
  classes=np.unique(data[:,-1]) 
  size=len(data)
  # print(data.shape)
  score=0
  for class_values in classes:
    score =score + np.square(np.count_nonzero(data[:,-1]== class_values)/size)
  gini=1-score
  return gini



  


def information_gain(dataset):
  # print(dataset.shape)
  percent=[10,20,30,40,50,60,70,80,90]
  i=-1
  gain=-9999
  left_data= None
  right_data= None
  new=[]
  datafeatures=dataset[:,0:dataset.shape[1]-1]
  #print(dataset.shape[1])
  left_gini,right_gini=0,0
  # value
  # index_column
  for column in datafeatures.T:

    i+=1
    # new=np.column_stack((features_train[:,i],labels_train))

    n_instances=float(len(dataset))
    if(n_instances<=1):
      continue
    gini_column=gini_number(dataset[:,[i,-1]])
    for percentile in percent:
      
      
      new=np.argsort(dataset[:,i])
      split=np.percentile(dataset[:,i],percentile)
      left=dataset[dataset[:,i]<split]
      left_size=float(len(left))
      right=dataset[dataset[:,i]>=split]
      right_size=float(len(right))
      # if(left_size > 0):
      left_gini=gini_number(left)
      # if (right_size > 0):
      right_gini=gini_number(right)
      weighted_gini=left_gini*(left_size/n_instances)+right_gini*(right_size/n_instances)
      info_gain=gini_column-weighted_gini
      if(info_gain>gain):
        gain,left_data,right_data,index_column,value=info_gain,left,right,i,split
  # print(index_column,value)
  return {'gain':gain,'left':left_data,'right':right_data,'index':index_column,'value':value}

def splitting(node,max_depth):
  # print(type(node['left']))
  # print(node['left'])
  depth=10
  minsize=2   
  left=node['left']
  right=node['right']
  del(node['left'])
  del(node['right'])
  left_label=left[:,-1]
  left_label=left_label.astype(int)
  right_label=right[:,-1]
  right_label=right_label.astype(int)
  values=[]
  if(len(left)==0 or len(right)==0):
    values=np.concatenate((left,right))
    vl=values[:,-1].astype(int)
    final_label=np.bincount(vl).argmax()
    node['left']=node['right']=final_label
    # print(node['left'])
    return
  if(max_depth>=depth):
    node['left']=np.bincount(left_label).argmax()
    # print(node['left'])
    node['right']=np.bincount(right_label).argmax()
    # print(node['right'])
    return
  if(minsize>=len(left)):
    node['left']=np.bincount(left_label).argmax()
    # print(node['left'])
  else:
    node['left']=information_gain(left)
    d=max_depth+1
    splitting(node['left'],d)
  if(minsize>=len(right)):
    node['right']=np.bincount(right_label).argmax()
    # print(node['right'])
  else:
    node['right']=information_gain(right)
    d=max_depth+1
    splitting(node['right'],d)
  # if(minsize<=right(left)):
  #   node[2]=np.bincount(right_label).argmax()

def predictions(root,row):
  if (row[root['index']]>root['value']):
    if isinstance(root['right'],dict):
      pred_val=predictions(root['right'],row)
    else:
      #print(root['right'])
      pred_val=root['right']
  else:
    if isinstance(root['left'],dict):
      pred_val=predictions(root['left'],row)
    else:
      #print(root['left'])
      pred_val=root['left']
  return pred_val


def decision_tree(data,test):
  
  node=information_gain(data)
  splitting(node,1)
  #print(node)
  test_predictions=[]
  for row in test:
    predicted=predictions(node,row)
    #print(predicted)
    test_predictions=np.append(test_predictions,predicted)
  return test_predictions
  # print(node)



# node=information_gain(data.values)
# decision_tree(features_train,labels_train,features_test)
#print()
  



In [91]:
def RandomForest(X_train,Y_train,X_test):
  epochs=10
  total_predictions=[]
  predicted_label=[]
  for i in range(epochs):
    features_for_split=np.sqrt(np.size(X_train,1)) #7 features
    #print(features_for_split)
    index=np.arange(X_train.shape[1])
    random_sample=np.random.choice(index,size=features_for_split.astype(int),replace=True)
    random_features=features_train[:,random_sample]
    #print(random_features.shape)
    test_features=X_test[:,random_sample]
    total_data=np.column_stack((random_features,Y_train))
    index_bootstrap=np.arange(X_train.shape[0])
    bootstrap_sample=np.random.choice(index_bootstrap,X_train.shape[0],replace=True)
    
    bootstrap_data=total_data[bootstrap_sample,:]
    #print(bootstrap_data.shape)
    total_predictions=np.append(total_predictions,decision_tree(bootstrap_data,test_features))
    # print(total_predictions.shape)
  total_predictions=total_predictions.reshape(epochs,X_test.shape[0])
  total_predictions=total_predictions.astype(int)
  # print(total_predictions)
  for row in total_predictions.T:
    predicted_label=np.append(predicted_label,np.bincount(row).argmax())
  return predicted_label
  
  
# print(labels_test.shape)
labels_predict=RandomForest(features_train,labels_train,features_test)
# print(labels_predict.shape)
print(accuracy_score(labels_test,labels_predict))
  
    # """
    # :type X_train: numpy.ndarray
    # :type X_test: numpy.ndarray
    # :type Y_train: numpy.ndarray
    
    # :rtype: numpy.ndarray
    # """

0.9146728515625


Pooja

In [78]:
def PCA(X_train,N):
    mean_Val = np.mean(X_train)
    X_train_mean=X_train-mean_Val
    u,s,vh = np.linalg.svd(X_train_mean, full_matrices=False)
    vh=vh.T
    S=np.diag(s)
    PCA_array = u[:, 0:N].dot(S[0:N, 0:N])
    return PCA_array
    # """
    # :type X_train: numpy.ndarray
    # :type N: int
    # :rtype: numpy.ndarray
    # """

[[-1.80899866 -0.97319046 -0.5198029  -0.13335396  0.01226552]
 [-1.70718706 -0.75001261 -0.23565801 -0.06914143 -0.0288503 ]
 [-1.75438486  0.08561008  0.1374438   0.12996271  0.04488621]
 ...
 [-1.91909963  0.70648457 -0.17498945  0.00307458 -0.14257381]
 [-1.72978258 -0.47746372  0.06421288  0.1703747   0.10250725]
 [-1.89899469  0.20191737 -0.23136465  0.08107682  0.05495291]]


Deepesh

In [0]:
def Kmeans(X_train,N):
    """
    :type X_train: numpy.ndarray
    :type N: int
    :rtype: List[numpy.ndarray]
    """

In [0]:
def SklearnSupervisedLearning(X_train,Y_train,X_test):
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """

In [0]:
def SklearnVotingClassifier(X_train,Y_train,X_test):
    
    """
    :type X_train: numpy.ndarray
    :type X_test: numpy.ndarray
    :type Y_train: numpy.ndarray
    
    :rtype: List[numpy.ndarray] 
    """


"""
Create your own custom functions for Matplotlib visualization of hyperparameter search. 
Make sure that plots are labeled and proper legends are used
"""